### ISSUE TITLE
[FEAT] - Add Sema's Discord in the `contact_fields` field

### ISSUE THREAD

**Issue by Panquesito7** [Semalab/oswc-query-bot#3]
### What feature would you like to see?

**Description**

As added in other repositories, the Discord link should be added
in the `contact_fields` field in the issue template configuration.

_If you have already forked the repository, skip to step 3_

1. Fork the repository [here](https://github.com/Semalab/oswc-query-bot/fork)
2. Go to your fork recently created.
3. Make a new branch named `discord_link`.
4. Once you've created the branch, go to `.github/ISSUE_TEMPLATE`, and open `config.yml`.
5. At the bottom, add the following code below:

```yaml
contact_links:
  - name: Questions
    url: https://discord.gg/Byjr6rdBUZ
    about: Any questions or comments you have, let us know on our Discord server.
```

6. Make a PR in this repository. If not sure how, see the [GitHub Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).
7. You're done now! You just need to wait for the maintainers to review your PR and merge it.

If you need any help, comment below and we will help you. 🙂 

### Additional information

This is a good first issue. Please leave it open to beginners and first-time contributors. 🙂
